### ISSUE TITLE
Add to data view fields: field identifier

### ISSUE THREAD

**Issue by EitanBlumin** [EitanBlumin/CRUDE-ASP#108]
In addition to FieldSource and FieldLabel, we'll also need FieldName or FieldIdentifier. Something we could use when referencing the field in expressions, URL filters and JavaScript functions, which would identify a dataview field, but not necessarily betray its actual database column name, nor be too abstract like the word field and a number.

**Subtasks**

- [x] New column in portal.DataViewFields
- [ ] Unique constraint
- [x] Use it during column initialization, instead of Field_123
- [x] Use it as id of input fields
- [X] Use it as search parameter and URL parameter
